# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='type',
            new_name='tag',
        ),
    ]
