# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=60, verbose_name='验证码'),
        ),
    ]
