# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171119_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='是否已确认'),
        ),
    ]
